/*
 * --------------------------------------------------------------------------------------------------------------------
 * <copyright company="Aspose">
 *   Copyright (c) 2018 Aspose.Slides for Cloud
 * </copyright>
 * <summary>
 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 * 
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 * 
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 * </summary>
 * --------------------------------------------------------------------------------------------------------------------
 */

package asposeslidescloud
// CombinedShapeType : 
type CombinedShapeType string

// List of CombinedShapeType CombinedShapeType
const (
	CombinedShapeType_CUSTOM CombinedShapeType = "Custom"
	CombinedShapeType_LINE CombinedShapeType = "Line"
	CombinedShapeType_LINE_INVERSE CombinedShapeType = "LineInverse"
	CombinedShapeType_TRIANGLE CombinedShapeType = "Triangle"
	CombinedShapeType_RIGHT_TRIANGLE CombinedShapeType = "RightTriangle"
	CombinedShapeType_RECTANGLE CombinedShapeType = "Rectangle"
	CombinedShapeType_DIAMOND CombinedShapeType = "Diamond"
	CombinedShapeType_PARALLELOGRAM CombinedShapeType = "Parallelogram"
	CombinedShapeType_TRAPEZOID CombinedShapeType = "Trapezoid"
	CombinedShapeType_NON_ISOSCELES_TRAPEZOID CombinedShapeType = "NonIsoscelesTrapezoid"
	CombinedShapeType_PENTAGON CombinedShapeType = "Pentagon"
	CombinedShapeType_HEXAGON CombinedShapeType = "Hexagon"
	CombinedShapeType_HEPTAGON CombinedShapeType = "Heptagon"
	CombinedShapeType_OCTAGON CombinedShapeType = "Octagon"
	CombinedShapeType_DECAGON CombinedShapeType = "Decagon"
	CombinedShapeType_DODECAGON CombinedShapeType = "Dodecagon"
	CombinedShapeType_FOUR_POINTED_STAR CombinedShapeType = "FourPointedStar"
	CombinedShapeType_FIVE_POINTED_STAR CombinedShapeType = "FivePointedStar"
	CombinedShapeType_SIX_POINTED_STAR CombinedShapeType = "SixPointedStar"
	CombinedShapeType_SEVEN_POINTED_STAR CombinedShapeType = "SevenPointedStar"
	CombinedShapeType_EIGHT_POINTED_STAR CombinedShapeType = "EightPointedStar"
	CombinedShapeType_TEN_POINTED_STAR CombinedShapeType = "TenPointedStar"
	CombinedShapeType_TWELVE_POINTED_STAR CombinedShapeType = "TwelvePointedStar"
	CombinedShapeType_SIXTEEN_POINTED_STAR CombinedShapeType = "SixteenPointedStar"
	CombinedShapeType_TWENTY_FOUR_POINTED_STAR CombinedShapeType = "TwentyFourPointedStar"
	CombinedShapeType_THIRTY_TWO_POINTED_STAR CombinedShapeType = "ThirtyTwoPointedStar"
	CombinedShapeType_ROUND_CORNER_RECTANGLE CombinedShapeType = "RoundCornerRectangle"
	CombinedShapeType_ONE_ROUND_CORNER_RECTANGLE CombinedShapeType = "OneRoundCornerRectangle"
	CombinedShapeType_TWO_SAMESIDE_ROUND_CORNER_RECTANGLE CombinedShapeType = "TwoSamesideRoundCornerRectangle"
	CombinedShapeType_TWO_DIAGONAL_ROUND_CORNER_RECTANGLE CombinedShapeType = "TwoDiagonalRoundCornerRectangle"
	CombinedShapeType_ONE_SNIP_ONE_ROUND_CORNER_RECTANGLE CombinedShapeType = "OneSnipOneRoundCornerRectangle"
	CombinedShapeType_ONE_SNIP_CORNER_RECTANGLE CombinedShapeType = "OneSnipCornerRectangle"
	CombinedShapeType_TWO_SAMESIDE_SNIP_CORNER_RECTANGLE CombinedShapeType = "TwoSamesideSnipCornerRectangle"
	CombinedShapeType_TWO_DIAGONAL_SNIP_CORNER_RECTANGLE CombinedShapeType = "TwoDiagonalSnipCornerRectangle"
	CombinedShapeType_PLAQUE CombinedShapeType = "Plaque"
	CombinedShapeType_ELLIPSE CombinedShapeType = "Ellipse"
	CombinedShapeType_TEARDROP CombinedShapeType = "Teardrop"
	CombinedShapeType_HOME_PLATE CombinedShapeType = "HomePlate"
	CombinedShapeType_CHEVRON CombinedShapeType = "Chevron"
	CombinedShapeType_PIE_WEDGE CombinedShapeType = "PieWedge"
	CombinedShapeType_PIE CombinedShapeType = "Pie"
	CombinedShapeType_BLOCK_ARC CombinedShapeType = "BlockArc"
	CombinedShapeType_DONUT CombinedShapeType = "Donut"
	CombinedShapeType_NO_SMOKING CombinedShapeType = "NoSmoking"
	CombinedShapeType_RIGHT_ARROW CombinedShapeType = "RightArrow"
	CombinedShapeType_LEFT_ARROW CombinedShapeType = "LeftArrow"
	CombinedShapeType_UP_ARROW CombinedShapeType = "UpArrow"
	CombinedShapeType_DOWN_ARROW CombinedShapeType = "DownArrow"
	CombinedShapeType_STRIPED_RIGHT_ARROW CombinedShapeType = "StripedRightArrow"
	CombinedShapeType_NOTCHED_RIGHT_ARROW CombinedShapeType = "NotchedRightArrow"
	CombinedShapeType_BENT_UP_ARROW CombinedShapeType = "BentUpArrow"
	CombinedShapeType_LEFT_RIGHT_ARROW CombinedShapeType = "LeftRightArrow"
	CombinedShapeType_UP_DOWN_ARROW CombinedShapeType = "UpDownArrow"
	CombinedShapeType_LEFT_UP_ARROW CombinedShapeType = "LeftUpArrow"
	CombinedShapeType_LEFT_RIGHT_UP_ARROW CombinedShapeType = "LeftRightUpArrow"
	CombinedShapeType_QUAD_ARROW CombinedShapeType = "QuadArrow"
	CombinedShapeType_CALLOUT_LEFT_ARROW CombinedShapeType = "CalloutLeftArrow"
	CombinedShapeType_CALLOUT_RIGHT_ARROW CombinedShapeType = "CalloutRightArrow"
	CombinedShapeType_CALLOUT_UP_ARROW CombinedShapeType = "CalloutUpArrow"
	CombinedShapeType_CALLOUT_DOWN_ARROW CombinedShapeType = "CalloutDownArrow"
	CombinedShapeType_CALLOUT_LEFT_RIGHT_ARROW CombinedShapeType = "CalloutLeftRightArrow"
	CombinedShapeType_CALLOUT_UP_DOWN_ARROW CombinedShapeType = "CalloutUpDownArrow"
	CombinedShapeType_CALLOUT_QUAD_ARROW CombinedShapeType = "CalloutQuadArrow"
	CombinedShapeType_BENT_ARROW CombinedShapeType = "BentArrow"
	CombinedShapeType_U_TURN_ARROW CombinedShapeType = "UTurnArrow"
	CombinedShapeType_CIRCULAR_ARROW CombinedShapeType = "CircularArrow"
	CombinedShapeType_LEFT_CIRCULAR_ARROW CombinedShapeType = "LeftCircularArrow"
	CombinedShapeType_LEFT_RIGHT_CIRCULAR_ARROW CombinedShapeType = "LeftRightCircularArrow"
	CombinedShapeType_CURVED_RIGHT_ARROW CombinedShapeType = "CurvedRightArrow"
	CombinedShapeType_CURVED_LEFT_ARROW CombinedShapeType = "CurvedLeftArrow"
	CombinedShapeType_CURVED_UP_ARROW CombinedShapeType = "CurvedUpArrow"
	CombinedShapeType_CURVED_DOWN_ARROW CombinedShapeType = "CurvedDownArrow"
	CombinedShapeType_SWOOSH_ARROW CombinedShapeType = "SwooshArrow"
	CombinedShapeType_CUBE CombinedShapeType = "Cube"
	CombinedShapeType_CAN CombinedShapeType = "Can"
	CombinedShapeType_LIGHTNING_BOLT CombinedShapeType = "LightningBolt"
	CombinedShapeType_HEART CombinedShapeType = "Heart"
	CombinedShapeType_SUN CombinedShapeType = "Sun"
	CombinedShapeType_MOON CombinedShapeType = "Moon"
	CombinedShapeType_SMILEY_FACE CombinedShapeType = "SmileyFace"
	CombinedShapeType_IRREGULAR_SEAL1 CombinedShapeType = "IrregularSeal1"
	CombinedShapeType_IRREGULAR_SEAL2 CombinedShapeType = "IrregularSeal2"
	CombinedShapeType_FOLDED_CORNER CombinedShapeType = "FoldedCorner"
	CombinedShapeType_BEVEL CombinedShapeType = "Bevel"
	CombinedShapeType_FRAME CombinedShapeType = "Frame"
	CombinedShapeType_HALF_FRAME CombinedShapeType = "HalfFrame"
	CombinedShapeType_CORNER CombinedShapeType = "Corner"
	CombinedShapeType_DIAGONAL_STRIPE CombinedShapeType = "DiagonalStripe"
	CombinedShapeType_CHORD CombinedShapeType = "Chord"
	CombinedShapeType_CURVED_ARC CombinedShapeType = "CurvedArc"
	CombinedShapeType_LEFT_BRACKET CombinedShapeType = "LeftBracket"
	CombinedShapeType_RIGHT_BRACKET CombinedShapeType = "RightBracket"
	CombinedShapeType_LEFT_BRACE CombinedShapeType = "LeftBrace"
	CombinedShapeType_RIGHT_BRACE CombinedShapeType = "RightBrace"
	CombinedShapeType_BRACKET_PAIR CombinedShapeType = "BracketPair"
	CombinedShapeType_BRACE_PAIR CombinedShapeType = "BracePair"
	CombinedShapeType_STRAIGHT_CONNECTOR1 CombinedShapeType = "StraightConnector1"
	CombinedShapeType_BENT_CONNECTOR2 CombinedShapeType = "BentConnector2"
	CombinedShapeType_BENT_CONNECTOR3 CombinedShapeType = "BentConnector3"
	CombinedShapeType_BENT_CONNECTOR4 CombinedShapeType = "BentConnector4"
	CombinedShapeType_BENT_CONNECTOR5 CombinedShapeType = "BentConnector5"
	CombinedShapeType_CURVED_CONNECTOR2 CombinedShapeType = "CurvedConnector2"
	CombinedShapeType_CURVED_CONNECTOR3 CombinedShapeType = "CurvedConnector3"
	CombinedShapeType_CURVED_CONNECTOR4 CombinedShapeType = "CurvedConnector4"
	CombinedShapeType_CURVED_CONNECTOR5 CombinedShapeType = "CurvedConnector5"
	CombinedShapeType_CALLOUT1 CombinedShapeType = "Callout1"
	CombinedShapeType_CALLOUT2 CombinedShapeType = "Callout2"
	CombinedShapeType_CALLOUT3 CombinedShapeType = "Callout3"
	CombinedShapeType_CALLOUT1_WITH_ACCENT CombinedShapeType = "Callout1WithAccent"
	CombinedShapeType_CALLOUT2_WITH_ACCENT CombinedShapeType = "Callout2WithAccent"
	CombinedShapeType_CALLOUT3_WITH_ACCENT CombinedShapeType = "Callout3WithAccent"
	CombinedShapeType_CALLOUT1_WITH_BORDER CombinedShapeType = "Callout1WithBorder"
	CombinedShapeType_CALLOUT2_WITH_BORDER CombinedShapeType = "Callout2WithBorder"
	CombinedShapeType_CALLOUT3_WITH_BORDER CombinedShapeType = "Callout3WithBorder"
	CombinedShapeType_CALLOUT1_WITH_BORDER_AND_ACCENT CombinedShapeType = "Callout1WithBorderAndAccent"
	CombinedShapeType_CALLOUT2_WITH_BORDER_AND_ACCENT CombinedShapeType = "Callout2WithBorderAndAccent"
	CombinedShapeType_CALLOUT3_WITH_BORDER_AND_ACCENT CombinedShapeType = "Callout3WithBorderAndAccent"
	CombinedShapeType_CALLOUT_WEDGE_RECTANGLE CombinedShapeType = "CalloutWedgeRectangle"
	CombinedShapeType_CALLOUT_WEDGE_ROUND_RECTANGLE CombinedShapeType = "CalloutWedgeRoundRectangle"
	CombinedShapeType_CALLOUT_WEDGE_ELLIPSE CombinedShapeType = "CalloutWedgeEllipse"
	CombinedShapeType_CALLOUT_CLOUD CombinedShapeType = "CalloutCloud"
	CombinedShapeType_CLOUD CombinedShapeType = "Cloud"
	CombinedShapeType_RIBBON CombinedShapeType = "Ribbon"
	CombinedShapeType_RIBBON2 CombinedShapeType = "Ribbon2"
	CombinedShapeType_ELLIPSE_RIBBON CombinedShapeType = "EllipseRibbon"
	CombinedShapeType_ELLIPSE_RIBBON2 CombinedShapeType = "EllipseRibbon2"
	CombinedShapeType_LEFT_RIGHT_RIBBON CombinedShapeType = "LeftRightRibbon"
	CombinedShapeType_VERTICAL_SCROLL CombinedShapeType = "VerticalScroll"
	CombinedShapeType_HORIZONTAL_SCROLL CombinedShapeType = "HorizontalScroll"
	CombinedShapeType_WAVE CombinedShapeType = "Wave"
	CombinedShapeType_DOUBLE_WAVE CombinedShapeType = "DoubleWave"
	CombinedShapeType_PLUS CombinedShapeType = "Plus"
	CombinedShapeType_PROCESS_FLOW CombinedShapeType = "ProcessFlow"
	CombinedShapeType_DECISION_FLOW CombinedShapeType = "DecisionFlow"
	CombinedShapeType_INPUT_OUTPUT_FLOW CombinedShapeType = "InputOutputFlow"
	CombinedShapeType_PREDEFINED_PROCESS_FLOW CombinedShapeType = "PredefinedProcessFlow"
	CombinedShapeType_INTERNAL_STORAGE_FLOW CombinedShapeType = "InternalStorageFlow"
	CombinedShapeType_DOCUMENT_FLOW CombinedShapeType = "DocumentFlow"
	CombinedShapeType_MULTI_DOCUMENT_FLOW CombinedShapeType = "MultiDocumentFlow"
	CombinedShapeType_TERMINATOR_FLOW CombinedShapeType = "TerminatorFlow"
	CombinedShapeType_PREPARATION_FLOW CombinedShapeType = "PreparationFlow"
	CombinedShapeType_MANUAL_INPUT_FLOW CombinedShapeType = "ManualInputFlow"
	CombinedShapeType_MANUAL_OPERATION_FLOW CombinedShapeType = "ManualOperationFlow"
	CombinedShapeType_CONNECTOR_FLOW CombinedShapeType = "ConnectorFlow"
	CombinedShapeType_PUNCHED_CARD_FLOW CombinedShapeType = "PunchedCardFlow"
	CombinedShapeType_PUNCHED_TAPE_FLOW CombinedShapeType = "PunchedTapeFlow"
	CombinedShapeType_SUMMING_JUNCTION_FLOW CombinedShapeType = "SummingJunctionFlow"
	CombinedShapeType_OR_FLOW CombinedShapeType = "OrFlow"
	CombinedShapeType_COLLATE_FLOW CombinedShapeType = "CollateFlow"
	CombinedShapeType_SORT_FLOW CombinedShapeType = "SortFlow"
	CombinedShapeType_EXTRACT_FLOW CombinedShapeType = "ExtractFlow"
	CombinedShapeType_MERGE_FLOW CombinedShapeType = "MergeFlow"
	CombinedShapeType_OFFLINE_STORAGE_FLOW CombinedShapeType = "OfflineStorageFlow"
	CombinedShapeType_ONLINE_STORAGE_FLOW CombinedShapeType = "OnlineStorageFlow"
	CombinedShapeType_MAGNETIC_TAPE_FLOW CombinedShapeType = "MagneticTapeFlow"
	CombinedShapeType_MAGNETIC_DISK_FLOW CombinedShapeType = "MagneticDiskFlow"
	CombinedShapeType_MAGNETIC_DRUM_FLOW CombinedShapeType = "MagneticDrumFlow"
	CombinedShapeType_DISPLAY_FLOW CombinedShapeType = "DisplayFlow"
	CombinedShapeType_DELAY_FLOW CombinedShapeType = "DelayFlow"
	CombinedShapeType_ALTERNATE_PROCESS_FLOW CombinedShapeType = "AlternateProcessFlow"
	CombinedShapeType_OFF_PAGE_CONNECTOR_FLOW CombinedShapeType = "OffPageConnectorFlow"
	CombinedShapeType_BLANK_BUTTON CombinedShapeType = "BlankButton"
	CombinedShapeType_HOME_BUTTON CombinedShapeType = "HomeButton"
	CombinedShapeType_HELP_BUTTON CombinedShapeType = "HelpButton"
	CombinedShapeType_INFORMATION_BUTTON CombinedShapeType = "InformationButton"
	CombinedShapeType_FORWARD_OR_NEXT_BUTTON CombinedShapeType = "ForwardOrNextButton"
	CombinedShapeType_BACK_OR_PREVIOUS_BUTTON CombinedShapeType = "BackOrPreviousButton"
	CombinedShapeType_END_BUTTON CombinedShapeType = "EndButton"
	CombinedShapeType_BEGINNING_BUTTON CombinedShapeType = "BeginningButton"
	CombinedShapeType_RETURN_BUTTON CombinedShapeType = "ReturnButton"
	CombinedShapeType_DOCUMENT_BUTTON CombinedShapeType = "DocumentButton"
	CombinedShapeType_SOUND_BUTTON CombinedShapeType = "SoundButton"
	CombinedShapeType_MOVIE_BUTTON CombinedShapeType = "MovieButton"
	CombinedShapeType_GEAR6 CombinedShapeType = "Gear6"
	CombinedShapeType_GEAR9 CombinedShapeType = "Gear9"
	CombinedShapeType_FUNNEL CombinedShapeType = "Funnel"
	CombinedShapeType_PLUS_MATH CombinedShapeType = "PlusMath"
	CombinedShapeType_MINUS_MATH CombinedShapeType = "MinusMath"
	CombinedShapeType_MULTIPLY_MATH CombinedShapeType = "MultiplyMath"
	CombinedShapeType_DIVIDE_MATH CombinedShapeType = "DivideMath"
	CombinedShapeType_EQUAL_MATH CombinedShapeType = "EqualMath"
	CombinedShapeType_NOT_EQUAL_MATH CombinedShapeType = "NotEqualMath"
	CombinedShapeType_CORNER_TABS CombinedShapeType = "CornerTabs"
	CombinedShapeType_SQUARE_TABS CombinedShapeType = "SquareTabs"
	CombinedShapeType_PLAQUE_TABS CombinedShapeType = "PlaqueTabs"
	CombinedShapeType_CHART_X CombinedShapeType = "ChartX"
	CombinedShapeType_CHART_STAR CombinedShapeType = "ChartStar"
	CombinedShapeType_CHART_PLUS CombinedShapeType = "ChartPlus"
	CombinedShapeType_CHART CombinedShapeType = "Chart"
	CombinedShapeType_TABLE CombinedShapeType = "Table"
	CombinedShapeType_PICTURE_FRAME CombinedShapeType = "PictureFrame"
	CombinedShapeType_VIDEO_FRAME CombinedShapeType = "VideoFrame"
	CombinedShapeType_AUDIO_FRAME CombinedShapeType = "AudioFrame"
	CombinedShapeType_DIAGRAM CombinedShapeType = "Diagram"
	CombinedShapeType_OLE_OBJECT_FRAME CombinedShapeType = "OleObjectFrame"
	CombinedShapeType_GROUP_SHAPE CombinedShapeType = "GroupShape"
	CombinedShapeType_GRAPHICAL_OBJECT CombinedShapeType = "GraphicalObject"
	CombinedShapeType_NOT_DEFINED CombinedShapeType = "NotDefined"
)